# Generated by Django 5.0.1 on 2024-02-10 08:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('restricted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extend_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actuall_name', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('profile_pic', models.ImageField(default='static/images/DefaultAvatar.jpg', upload_to='')),
                ('checkmark', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('User_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=10)),
                ('description', models.TextField()),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.community')),
            ],
        ),
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_score', models.IntegerField(blank=True, null=True)),
                ('restricted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('Upvote', models.IntegerField()),
                ('Downvote', models.IntegerField()),
                ('dateofpost', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 8, 35, 11, 830371))),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('Community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.community')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.tags')),
            ],
        ),
    ]
