# Generated by Django 5.0.1 on 2024-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_base_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_user',
            name='profile_pic',
            field=models.ImageField(default='static/images/Default_Stuff/DefaultAvatar.jpg', upload_to='static/UserGenerated/profilepic'),
        ),
    ]
