# Generated by Django 5.0.1 on 2024-02-13 12:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('restricted', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('post_score', models.IntegerField(blank=True, null=True)),
                ('restricted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('Upvote', models.IntegerField()),
                ('Downvote', models.IntegerField()),
                ('dateofpost', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
