# Generated by Django 5.0.1 on 2024-02-11 12:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('restricted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=10)),
                ('description', models.TextField()),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LandingPages.community')),
            ],
        ),
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('post_score', models.IntegerField(blank=True, null=True)),
                ('restricted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('Upvote', models.IntegerField()),
                ('Downvote', models.IntegerField()),
                ('dateofpost', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('Community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LandingPages.community')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LandingPages.tags')),
            ],
        ),
    ]
