# Generated by Django 5.0.1 on 2024-03-03 17:06

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPages', '0003_community_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='description',
            field=models.CharField(default=builtins.print, max_length=100),
            preserve_default=False,
        ),
    ]
