# Generated by Django 5.0.1 on 2024-03-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPages', '0004_newpost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='Downvote',
        ),
        migrations.RemoveField(
            model_name='newpost',
            name='Upvote',
        ),
        migrations.RemoveField(
            model_name='newpost',
            name='post_score',
        ),
        migrations.AlterField(
            model_name='newpost',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
