# Generated by Django 5.0.1 on 2024-04-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPages', '0005_remove_newpost_downvote_remove_newpost_upvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='banner',
            field=models.ImageField(default='static/Default_Banner.jpg', upload_to='static/Post_Banner'),
        ),
    ]
